# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: school_index.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'school_index.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12school_index.proto\x12\x0cschool_index\"b\n\x0bSchoolIndex\x12\x18\n\x10protocol_version\x18\x01 \x01(\x03\x12\x12\n\nversion_id\x18\x02 \x01(\t\x12%\n\x07schools\x18\x03 \x03(\x0b\x32\x14.school_index.School\"u\n\x06School\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07initial\x18\x03 \x01(\t\x12\x17\n\x0fresource_folder\x18\x04 \x01(\t\x12\'\n\x08\x61\x64\x61pters\x18\x05 \x03(\x0b\x32\x15.school_index.Adapter\"\xcc\x01\n\x07\x41\x64\x61pter\x12\x12\n\nadapter_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x64\x61pter_name\x18\x02 \x01(\t\x12/\n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32\x1d.school_index.AdapterCategory\x12\x15\n\rasset_js_path\x18\x04 \x01(\t\x12\x17\n\nimport_url\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x12\n\nmaintainer\x18\x07 \x01(\tB\r\n\x0b_import_url*o\n\x0f\x41\x64\x61pterCategory\x12\x1c\n\x18\x41\x44\x41PTER_CATEGORY_UNKNOWN\x10\x00\x12\x10\n\x0cGENERAL_TOOL\x10\x01\x12\x1a\n\x16\x42\x41\x43HELOR_AND_ASSOCIATE\x10\x02\x12\x10\n\x0cPOSTGRADUATE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'school_index_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADAPTERCATEGORY']._serialized_start=462
  _globals['_ADAPTERCATEGORY']._serialized_end=573
  _globals['_SCHOOLINDEX']._serialized_start=36
  _globals['_SCHOOLINDEX']._serialized_end=134
  _globals['_SCHOOL']._serialized_start=136
  _globals['_SCHOOL']._serialized_end=253
  _globals['_ADAPTER']._serialized_start=256
  _globals['_ADAPTER']._serialized_end=460
# @@protoc_insertion_point(module_scope)
