package com.xiaomanjun.sleepdownschedule

import com.xiaomanjun.sleepdownschedule.feature.widget.providers.TodayCoursesSquareWidgetProviderHost

class TodayCoursesSquareWidgetProvider : TodayCoursesSquareWidgetProviderHost()
