package com.xiaomanjun.sleepdownschedule

import com.xiaomanjun.sleepdownschedule.feature.widget.providers.TodayTomorrowWidgetProviderHost

class TodayTomorrowWidgetProvider : TodayTomorrowWidgetProviderHost()
