package com.xiaomanjun.sleepdownschedule

import com.xiaomanjun.sleepdownschedule.feature.widget.providers.TodayAssistantWidgetProviderHost

class TodayAssistantWidgetProvider : TodayAssistantWidgetProviderHost()
