name: Publish to GitHub Packages

on:
  push:
    branches: ["main"]
    tags: ["*"]
    paths:
      - "miuix-core/**"
      - "miuix-ui/**"
      - "miuix-preference/**"
      - "miuix-shader/**"
      - "miuix-blur/**"
      - "miuix-squircle/**"
      - "miuix-icons/**"
      - "miuix-navigation3-ui/**"
      - "build-plugins/**"
      - "gradle/**"
      - "settings.gradle.kts"
      - "build.gradle.kts"
      - "gradle.properties"

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_snapshot:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Publish SNAPSHOT to GitHub Packages
        run: ./gradlew --no-daemon --stacktrace publishAllPublicationsToGithubRepository --no-configuration-cache
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
